## This is an example config file for reference.
## best to put it in a folder and then also store the model there
## either data_dir or hf_dataset has to be part of the config
## you can specify an out_dir that it different from the config
## if no outdir is in the config, the path of the config will be taken as an outdir 
## this is where to model will be saved at the end
data_dir: ./path/to/json/files 
## OR
huggingface_url: https://huggingface.co/datasets/allenai/olmo-mix-1124 # or whatever
subset: #can be a list or a string, must be a subset for which a loader exists on hf hub.
  - wiki
  - arxiv
vector_size: 300 #same size as google news and other static embeddings
window: 5
min_count: 10 
max_sentences: 1000 
workers: 4 ## you can either put an int or  ALL, which will be num_cores - 1, or MAX which will be num_cores 
sg: 1 ## skip-gram, 0 for cbow
epochs: 5
buffered: False ## If True, will use one cpu core for predownloading batches.